@api = http://localhost:4002/api/auth

### sign in
POST {{api}}/login
Content-Type: application/json

{
    "username": "robertoss",
    "password": "121212"
}

### sign up
POST {{api}}
Content-Type: application/json

{
    "email": "robertoss@correo.com",
    "username": "robertoss",
    "password": "121212"
}

### renovar token
{{api}}
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmY2NWJhNWI2NGJlMDIzMWEwOTIyNyIsImlhdCI6MTY2NDA1MDYyOCwiZXhwIjoxNjY0MDY1MDI4fQ.4-rwzllnZpB6XWXwZX-45RQ5i7KIJX002y_EuR0jUM4