@api = http://localhost:4002/api/auth

### sign in
POST {{api}}/login
Content-Type: application/json

{
    "username": "ucamp",
    "password": "ucamp"
}

### sign up
POST {{api}}
Content-Type: application/json

{
    "email": "jesuss@correo.com",
    "username": "jessus",
    "password": "121212"
}

### renovar token
{{api}}
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzBhMmVlYTk3MmNlOGIzOWQ5YjZlYyIsImlhdCI6MTY2NDEzMTgyMiwiZXhwIjoxNjY0MTQ2MjIyfQ.CqFl6H_iqxBGhRSE_kS7U9X7rRGxt3Sfza7szJs46po